load("@io_bazel_rules_go//go:def.bzl", "go_library")

go_library(
    name = "meta",
    srcs = ["meta.go"],
    importpath = "github.com/levintp/observer/internal/meta",
    visibility = ["//observer:__subpackages__"],
    deps = ["//observer/internal/log"],
)
